### PR TITLE
Add support for RichEditor

### PR DESCRIPTION
**Pull request by jeremymouton**
Move RichEditor fields to secondary tabs navigation.

### CODE REVIEW

**Comment by jimcottrell** [comment]
That seems strange that there's just a 'richeditor' value in the array.  Is it really the existence of a key we should be checking for?

**Comment by jeremymouton** [comment]
The key is `type` https://github.com/octobercms/library/blob/master/src/Parse/Syntax/Parser.php#L211

I'm trying to get Rich Editor fields to appear in the secondary nav, and this worked - although it might not be the best approach.

**Comment by jimcottrell** [comment]
Okay.  Then I'd prefer something more like:
`... || (array_key_exists('type', $field) && $field['type'] === 'richeditor')`
so we can be more specific.

**Comment by jimcottrell** [comment]
@jeremymouton I didn't notice this had been changed.  I'll merge.

**Pull request merged**
